### ISSUE TITLE
Strings containing null characters.

### ISSUE THREAD

**Issue by Brandon-T** [Villavu/Simba#339]
Simba cannot print strings containing a null character. One example is the following:

```
var
  Str: String;
begin
  Str := 'hello' + #0 + 'world';

  writeln(Str);
  writeln('Length: ', Length(Str));
end.
```

For which the result is:

```
'hello'
Length: 11
```

It knows the length of the string is 11 characters but as soon as it hits a null character, it considers the string terminated. I do not believe this C like behaviour should be allowed because the string has a length. This may or may not be a problem with the `writeln` function and it may have more to do with the GUI (debug box), but I'm not sure.

**Comment by Olly-** [comment]
It's a bug? with TMemo http://i.imgur.com/FQ3VD8c.png

Works in a TListBox fine though, and I plan to one day change Simba's debug box to a ListBox so hopefully one day this will be 'fixed'.

**Comment by nielsAD** [comment]
Yeah, this is a Lazarus/Windows thingy. We could circumvent it by escaping \#0 perhaps, but not sure what we would show instead.

**Comment by R030t1** [comment]
Generally #0 has no glyph and is zero width, so if we want to fix the behavior inside of Simba we can strip #0 characters from strings. On some OSes and with some fonts the glyph will display as either a block, or a block with "0000" tiled inside of it.

**Comment by ollydev** [comment]
7 years later, in the upcoming simba1500 this is fixed!

![Simba-Win64_2qLZwuO4QE](https://user-images.githubusercontent.com/3413206/170630493-f422d16c-5ed7-463c-8973-d4d673387841.png)
