### ISSUE TITLE
Migrate bugs from bugs.villavu.com to github

### ISSUE THREAD

**Issue by MerlijnWajer** [Villavu/Simba#347]
Is there a mantisbt to github convertor out there somewhere?

**Comment by CynicRus** [comment]
https://noswap.com/blog/integrating-git-svn-with-mantisbt

**Comment by JohnPeel** [comment]
https://github.com/servalproject/serval-tools/blob/master/doc/sp-mantis2github.md

**Comment by Nazgand** [comment]
Does http://bugs.villavu.com/ even exist anymore?

**Comment by MerlijnWajer** [comment]
It may not be running right now, but I can bring it online for a migration.

**Comment by Nazgand** [comment]
Nice to know. I do not know how to do the migration; I simply thought that this issue could be closed because bugs.villavu.com disappeared.

**Comment by R030t1** [comment]
Has the old tracker ever been revived for migration?
