### ISSUE TITLE
Test scripts do not compile

### ISSUE THREAD

**Issue by nielsAD** [Villavu/Simba#384]
- [ ] Update scripts in `Tests/Lape`
- [ ] Remove `Tests/FPC` and `Tests/CPascal`. Maybe fix and move the scripts inside these folders
- [ ] Make sure scripts in `Example/` folder compile with Lape _[OPTIONAL]_

**Comment by JohnPeel** [comment]
Maybe we should remove the Tests/Lape, and just grab Lape's actual test scripts?

**Comment by JohnPeel** [comment]
Removed from milestone as it's not exactly urgent, or even needed for releases.
