### ISSUE TITLE
Lape Extensions

### ISSUE THREAD

**Issue by nielsAD** [Villavu/Simba#385]
Enable support for Extensions using the Lape interpreter. Will allow us to run Extensions on platforms other than Windows.

**Comment by R030t1** [comment]
Why is this feature currently Windows-specific?

**Comment by nielsAD** [comment]
With "this feature" I assume you mean extensions. At the time of writing extension support, Pascal Script didn't work properly on platforms other than Windows x86, so it was disabled on other platforms.

**Comment by R030t1** [comment]
I thought Pascal Script was deprecated or not included in Simba?

**Comment by nielsAD** [comment]
It still included (because of extensions, for example), but I guess it can be considered deprecated.

**Comment by R030t1** [comment]
So do extensions no longer exist? Are extensions only referred to because they are something that the Pascal Script engine can interface with?

**Comment by nielsAD** [comment]
Extensions still exist and Pascal Script is still used as interpreter for them. However, for the (historical) reason listed above, they are only enabled on Windows. Ideally we would also like to support (or switch entirely to) Lape as interpreter for extensions for consistency with the scripting engine and improved platform support.

**Comment by R030t1** [comment]
Has anyone looked at that to see what it would take?

**Comment by ollydev** [comment]
Some similar functionally can be added with packages.
https://github.com/Villavu/Simba/blob/simba1500/PACKAGES.md
