### ISSUE TITLE
Clean up repository

### ISSUE THREAD

**Issue by nielsAD** [Villavu/Simba#386]
- [ ] Remove deprecated brances
- [ ] Move items in `TODO` files to GitHub issues
- [ ] Remove CPascal plugins
- [ ] Remove deprecated/unused projects. In my opinion, all but the core projects should be removed (this means almost everything but `Simba`). Arguable: ~~`FormDesigner`~~, `lape-wrappers`, `libmml`, `OCRBench`, `OCRTool`, ~~`ScriptManager`~~.

**Comment by JohnPeel** [comment]
FormDesigner and ScriptManager are a part of Simba, though we could make them submodules.

**Comment by nielsAD** [comment]
Should be fine to keep them in. Got a bit confused by the location, thinking they were remains of "test" projects before they were merged into Simba.
