### ISSUE TITLE
Improve Code Insight

### ISSUE THREAD

**Issue by nielsAD** [Villavu/Simba#394]
- [ ] Share expression resolving code for ctrl+click, completion, param hints
- [ ] Recursively search for objects (i.e. expressions with more than one dot)
- [ ] Show param hints for nested calls, continue with outer hint when finishing the inner call
- [ ] Show overloaded param hints

**Comment by R030t1** [comment]
@nielsAD, @Olly-: Can you compare the desired code completion semantics with something that exists currently, like IntelliJ IDEA or Sublime Text?

**Comment by ollydev** [comment]
It's very much improved now. But still is hacked together and needs a rewrite eventually.
