### ISSUE TITLE
Export static class .Create functions

### ISSUE THREAD

**Issue by nielsAD** [Villavu/Simba#399]
Keep .Init() functions for now for backwards compatibility, but make clear they are deprecated. As all other class import functions are marked as `constref`, maybe we can wrap these calls into something like `addClassMethod` to do this automatically (as we have done with `addClassVar`).

**Comment by JohnPeel** [comment]
I actually made a addClassMethod, but it's so ugly trying to put the constref before overload and override...

**Comment by JohnPeel** [comment]
```
function TLapeCompilerHelper.addClassFunc(AHeader: lpString; Value: Pointer): TLapeGlobalVar;
var
  ParPos, SCPos: SizeInt;
begin
  ParPos := Pos(')', AHeader);
  if (ParPos > 0) then
  begin
    SCPos := ParPos + Pos(';', Copy(AHeader, ParPos + 1, Length(AHeader)));
    if (SCPos = ParPos) then
      SCPos := Length(AHeader);
  end else
    SCPos := Length(AHeader);

  Insert(' constref;', AHeader, SCPos + 1);
  Result := addGlobalFunc(AHeader, Value);

  // T_T Wai!!
  //TLapeType_MethodOfType(Result.VarType).Params.Items[0].ParType := lptConstRef;
end;
```

**Comment by nielsAD** [comment]
We might be able to get away with `Result.SelfParam := lptConstRef;`.

**Comment by JohnPeel** [comment]
@nielsAD You should start work on the "future parsing" thing I was talking about =)

**Comment by nielsAD** [comment]
@JohnPeel Lape 2.0! :stuck_out_tongue:

**Comment by ollydev** [comment]
Better late than never!
