### ISSUE TITLE
Support serial port access.

### ISSUE THREAD

**Issue by ghost** [Villavu/Simba#407]
A user has requested serial port access. It would be possible to use a library like Synapse or create custom OS bindings. My experience with Synapse is that while it is a cross-platform wrapper it can be hard to use. There may be something in the codebase more suitable, if that is the case I'm not aware of it.

For now, opening the file representing the port should work for either OS as long as the default settings agree with the connected device (`/dev/tty*` or `\\.\COM*`).

**Comment by MerlijnWajer** [comment]
This seems suitable:
http://wiki.freepascal.org/Hardware_Access#FPC_built_in_Serial_unit

**Comment by R030t1** [comment]
How are bindings for the necessary functions and data structures added?

**Comment by MerlijnWajer** [comment]
I think that the serial unit I linked also works on other platforms.

Look at the PSInc and LPInc directories on how you can add wrappers. We usually generate them, but you can also write them by hand. @JohnPeel knows.

**Comment by CynicRus** [comment]
Done as plugin: https://villavu.com/forum/showthread.php?t=176698&p=1453045#post1453045
